### ISSUE TITLE
WWW: Logo

### ISSUE THREAD

**Issue by suvozy** [swatantraorg/gandu.org#2]
# Google `G`

![g_of_google_1](https://cloud.githubusercontent.com/assets/5635088/15631450/156e44ce-2589-11e6-9473-7d9d5e123d51.gif)
https://commons.wikimedia.org/wiki/File:G_of_google_1.gif

![g_of_google_2](https://cloud.githubusercontent.com/assets/5635088/15631451/1570283e-2589-11e6-9081-c85b9ef2b94b.gif)
https://commons.wikimedia.org/wiki/File:G_of_google_2.gif

**Comment by suvozy** [comment]
![untitled-1-01](https://cloud.githubusercontent.com/assets/5635088/15631445/fef36256-2588-11e6-8759-2ed3d7b1273c.png)

**Comment by suvozy** [comment]
![screenshot 2016-05-29 10 42 26](https://cloud.githubusercontent.com/assets/5635088/15631478/17a5194c-258a-11e6-879b-152f76d29311.png)
https://twitter.com/Groupon/status/639547804256468993?ref_src=twsrc%5Etfw

![](https://s3.amazonaws.com/images.seroundtable.com/google-g-groupon-g-1441368832.gif)

**Comment by suvozit** [comment]
![tumblr_m8jk6ninjo1qzt4vjo1_r1_500](https://cloud.githubusercontent.com/assets/5635088/15631508/36d29f14-258b-11e6-898a-4a5cde56a3bc.gif)
> # There's nothing here.
> Whatever you were looking for doesn't currently exist at this address. Unless you were looking for this error page, in which case: Congrats! You totally found it.
> http://rickshawpuller.tumblr.com
